<#
.SYNOPSIS
Regenerates the custom-function table at the top of README.md.

.DESCRIPTION
The table is derived, not hand-maintained. Descriptions come from the $functions summary
array in the PowerShell profile - the same data printed at shell startup - so the README
and the startup banner can never disagree. Function names are resolved to their defining
file and line by parsing the AST, so the deep links stay correct as code moves.

Rerun after adding a function, renaming one, or editing a description:

    pwsh -File pwsh/Update-ReadmeFunctions.ps1

It rewrites only the block between the FUNCTIONS markers in README.md and is idempotent:
running it twice in a row produces no diff. -Check reports drift without writing, which is
what CI would call.

.PARAMETER Check
Exit 1 if README.md is out of date instead of rewriting it.
#>
[CmdletBinding()]
param([switch]$Check)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot   = Split-Path $PSScriptRoot -Parent
$profilePath = Join-Path $PSScriptRoot 'Microsoft.PowerShell_profile.ps1'
$modulePath  = Join-Path $PSScriptRoot 'DeskSwitch.psm1'
$readmePath  = Join-Path $repoRoot 'README.md'

$startMarker = '<!-- FUNCTIONS:START - generated by pwsh/Update-ReadmeFunctions.ps1, do not edit by hand -->'
$endMarker   = '<!-- FUNCTIONS:END -->'

function Get-FunctionIndex {
    <#
    Maps function name -> @{ File; Line }, for every function defined in the given files.
    #>
    param([string[]]$Path)

    $index = @{}
    foreach ($p in $Path) {
        if (-not (Test-Path $p)) { continue }
        $ast = [System.Management.Automation.Language.Parser]::ParseFile($p, [ref]$null, [ref]$null)
        $found = $ast.FindAll(
            { $args[0] -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)
        foreach ($f in $found) {
            # First definition wins; a name should not be defined twice anyway.
            if (-not $index.ContainsKey($f.Name)) {
                $index[$f.Name] = @{
                    File = (Resolve-Path $p).Path.Substring($repoRoot.Length + 1).Replace('\', '/')
                    Line = $f.Extent.StartLineNumber
                }
            }
        }
    }
    $index
}

function Get-SummaryEntry {
    <#
    Reads the $functions array out of the profile via the AST rather than by regex, so a
    description containing quotes or braces cannot break parsing.
    #>
    param([string]$Path)

    $ast = [System.Management.Automation.Language.Parser]::ParseFile($Path, [ref]$null, [ref]$null)
    $assign = $ast.FindAll({
            $args[0] -is [System.Management.Automation.Language.AssignmentStatementAst] -and
            $args[0].Left.Extent.Text -eq '$functions'
        }, $true) | Select-Object -First 1

    if (-not $assign) { throw "Could not find the `$functions summary array in $Path." }

    $entries = @()
    $hashes = $assign.Right.FindAll(
        { $args[0] -is [System.Management.Automation.Language.HashtableAst] }, $true)

    foreach ($h in $hashes) {
        $row = @{ Alias = ''; Name = ''; Desc = '' }
        foreach ($pair in $h.KeyValuePairs) {
            $key = $pair.Item1.Extent.Text.Trim('"', "'")
            $val = $pair.Item2.Extent.Text.Trim()
            # Strip the surrounding quotes of a simple string literal.
            if ($val.Length -ge 2 -and $val[0] -eq '"' -and $val[-1] -eq '"') { $val = $val.Substring(1, $val.Length - 2) }
            elseif ($val.Length -ge 2 -and $val[0] -eq "'" -and $val[-1] -eq "'") { $val = $val.Substring(1, $val.Length - 2) }
            if ($row.ContainsKey($key)) { $row[$key] = $val }
        }
        if ($row.Name) { $entries += [pscustomobject]$row }
    }
    $entries
}

function Format-Cell {
    # Escape the characters that would otherwise break a markdown table cell.
    param([string]$Text)
    $Text.Replace('\', '\\').Replace('|', '\|').Replace('`$', '$')
}

$index   = Get-FunctionIndex -Path @($profilePath, $modulePath)
$entries = @(Get-SummaryEntry -Path $profilePath)

if (-not $entries) { throw 'No function entries found.' }

$rows = foreach ($e in $entries) {
    $alias = if ($e.Alias) { '`' + $e.Alias + '`' } else { '' }

    $link = if ($index.ContainsKey($e.Name)) {
        '[`{0}`]({1}#L{2})' -f $e.Name, $index[$e.Name].File, $index[$e.Name].Line
    }
    else {
        # Defined somewhere not scanned; still list it rather than silently dropping it.
        '`' + $e.Name + '`'
    }

    '| {0} | {1} | {2} |' -f $alias, $link, (Format-Cell $e.Desc)
}

$missing = @($entries | Where-Object { -not $index.ContainsKey($_.Name) })

$block = @()
$block += $startMarker
$block += ''
$block += '| Alias | Function | What it does |'
$block += '| --- | --- | --- |'
$block += $rows
$block += ''
$block += '_Generated from the `$functions` summary in the profile - the same list printed at shell startup - by [`pwsh/Update-ReadmeFunctions.ps1`](pwsh/Update-ReadmeFunctions.ps1)._'
$block += ''
$block += $endMarker

$readme = Get-Content $readmePath -Raw
$newBlock = ($block -join "`n")

if ($readme -match [regex]::Escape($startMarker)) {
    $pattern = '(?s)' + [regex]::Escape($startMarker) + '.*?' + [regex]::Escape($endMarker)
    $updated = [regex]::Replace($readme, $pattern, { $newBlock })
}
else {
    # First run: insert directly after the H1 title.
    $lines = $readme -split "`r?`n"
    $titleIndex = 0
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '^#\s') { $titleIndex = $i; break }
    }
    $before = $lines[0..$titleIndex]
    $after  = $lines[($titleIndex + 1)..($lines.Count - 1)]
    $updated = (($before + @('') + $block + $after) -join "`n")
}

# Keep the file LF, matching .gitattributes.
$updated = $updated -replace "`r`n", "`n"

if ($Check) {
    if (($readme -replace "`r`n", "`n") -eq $updated) {
        Write-Host 'README function table is up to date.' -ForegroundColor Green
        exit 0
    }
    Write-Error 'README function table is out of date. Run: pwsh -File pwsh/Update-ReadmeFunctions.ps1'
    exit 1
}

[IO.File]::WriteAllText($readmePath, $updated, (New-Object Text.UTF8Encoding $false))

Write-Host "Wrote $($rows.Count) function rows to README.md" -ForegroundColor Green
if ($missing) {
    Write-Warning ("Not found in the scanned files, listed without a link: {0}" -f (($missing.Name) -join ', '))
}
